# Titanic - Machine Learning from Disaster



### Começando a entender a base

In [ ]:
# Importando o pandas
import pandas as pd

In [ ]:
# Visualizando a base de treino
treino = pd.read_csv('titanic_train.csv')
treino.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [ ]:
# Importando o ProfileReport do ydata-profiling
!pip install ydata-profiling
from ydata_profiling import ProfileReport

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.0/62.0 kB 2.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 400.1/400.1 kB 11.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 296.5/296.5 kB 21.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 679.0/679.0 kB 31.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 37.7/37.7 MB 46.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 105.4/105.4 kB 7.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.3/43.3 kB 3.2 MB/s eta 0:00:00
  Created wheel for htmlmin: filename=htmlmin-0.1.12-py3-none-any.whl size=27081 sha256=46ed9697d1b40ba872a63ba2bbd23da9c0099e52c0c80174a1bf3a037a336799
  Stored in directory: /root/.cache/pip/wheels/8d/55/1a/19cd535375ed1ede0c996405ebffe34b196d78e2d9545723a2
Successfully built htmlmin
  Attempting uninstall: scipy
    Found existing installation: scipy 1.16.1
    Uninstalling scipy-1.16.1:
     

In [ ]:
# Gerando a visualização
profile = ProfileReport(treino, title="Titanic - Relatório")


In [ ]:
# Criando o relatório
profile.to_file("Titanic - Relatório.html")

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]


100%|██████████| 12/12 [00:00<00:00, 37.55it/s]


Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

- **Agora vamos analisar essa base**

In [ ]:
# Verificando as informações da base
treino.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [ ]:
# Verificando o tipo dos dados
treino.dtypes.value_counts()

int64      5
object     5
float64    2
Name: count, dtype: int64

In [ ]:
# E os valores nulos
treino.isnull().sum().sort_values(ascending=False).head(5)

Cabin          687
Age            177
Embarked         2
PassengerId      0
Name             0
dtype: int64

- **Agora vamos visualizar a base de teste**

In [ ]:
# Visualizando a base de teste
teste = pd.read_csv('titanic_test')
teste.head(3)

PassengerId  Survived  Pclass                              Name     Sex  \
0          892         0       3                  Kelly, Mr. James    male   
1          893         1       3  Wilkes, Mrs. James (Ellen Needs)  female   
2          894         0       2         Myles, Mr. Thomas Francis    male   

    Age  SibSp  Parch  Ticket    Fare Cabin Embarked  
0  34.5      0      0  330911  7.8292   NaN        Q  
1  47.0      1      0  363272  7.0000   NaN        S  
2  62.0      0      0  240276  9.6875   NaN        Q

In [ ]:
# Verificando as informações da base
teste.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  418 non-null    int64  
 1   Survived     418 non-null    int64  
 2   Pclass       418 non-null    int64  
 3   Name         418 non-null    object 
 4   Sex          418 non-null    object 
 5   Age          332 non-null    float64
 6   SibSp        418 non-null    int64  
 7   Parch        418 non-null    int64  
 8   Ticket       418 non-null    object 
 9   Fare         417 non-null    float64
 10  Cabin        91 non-null     object 
 11  Embarked     418 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 39.3+ KB


In [ ]:
# Analisando os valores nulos
teste.isnull().sum().sort_values(ascending=False).head(5)

Cabin          327
Age             86
Fare             1
PassengerId      0
Name             0
dtype: int64

### Realizando os tratamentos iniciais dos dados

In [ ]:
# Verificando novamente valores vazios para a base de treino
treino.isnull().sum().sort_values(ascending=False).head(5)

Cabin          687
Age            177
Embarked         2
PassengerId      0
Name             0
dtype: int64

In [ ]:
# Retornando o shape da base
treino.shape

(891, 12)

In [ ]:
# Visualizando novamente a base
treino.head(4)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S

In [ ]:
# Verificando a cardinalidade dos dados
treino.nunique().sort_values(ascending=False)

PassengerId    891
Name           891
Ticket         681
Fare           248
Cabin          147
Age             88
SibSp            7
Parch            7
Embarked         3
Pclass           3
Survived         2
Sex              2
dtype: int64

In [ ]:
# Eliminando para a base de treino
treino = treino.drop(['Name', 'Ticket', 'Cabin'], axis=1)

In [ ]:
# Também eliminando para a base de teste
teste = teste.drop(['Name', 'Ticket', 'Cabin'], axis=1)

In [ ]:
# Verificando a média das idades para a base de treino
treino['Age'].mean()

np.float64(29.69911764705882)

In [ ]:
# Podemos agora selecionar as colunas com idade vazia e substituir por essa média
treino.loc[treino['Age'].isnull(), 'Age'] = treino['Age'].mean()


In [ ]:
# E fazendo o mesmo para a base de teste
teste.loc[teste['Age'].isnull(), 'Age'] = teste['Age'].mean()

In [ ]:
# Verificando os valores na coluna Embarked
treino['Embarked'].value_counts()

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [ ]:
# Selecionando a moda dessa coluna
treino['Embarked'].mode()[0]


'S'

In [ ]:
# Substituindo os valores vazios
treino.loc[treino['Embarked'].isnull(), 'Embarked'] = treino['Embarked'].mode()[0]

In [ ]:
# Verificando a média da coluna Fare para a base de teste
teste.loc[teste['Fare'].isnull(), 'Fare'] = teste['Fare'].mean()

In [ ]:
# Para a base de treino
treino.isnull().sum().sort_values(ascending=False).head(5)

PassengerId    0
Survived       0
Pclass         0
Sex            0
Age            0
dtype: int64

In [ ]:
# Para a base de teste
teste.isnull().sum().sort_values(ascending=False).head(5)

PassengerId    0
Survived       0
Pclass         0
Sex            0
Age            0
dtype: int64

### Considerando apenas as colunas que não são de texto

In [ ]:
# Verificando as colunas de texto na base de treino
col_treino_nr = treino.columns[treino.dtypes != 'object']
col_treino_nr

Index(['PassengerId', 'Survived', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare'], dtype='object')

In [ ]:
# Selecionando apenas os valores numéricos da base de treino
treino_nr = treino.loc[:,col_treino_nr]

In [ ]:
# E para a base de teste
col_teste_nr = teste.columns[teste.dtypes != 'object']
col_teste_nr

Index(['PassengerId', 'Survived', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare'], dtype='object')

In [ ]:
# e os valores numéricos da base de teste
teste_nr = teste.loc[:,col_teste_nr]

In [ ]:
# Importando o train_test_split
from sklearn.model_selection import train_test_split

In [ ]:
# Separando a base de treino em X e y
X = treino_nr.drop( ['PassengerId', 'Survived'], axis=1)
y = treino_nr['Survived']

In [ ]:
# Separando em treino e validação
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.33, random_state=42)

- Para a **árvore de classificação**

In [ ]:
# Fazendo a importação
from sklearn import tree

In [ ]:
# Criando o classificador
clf_ac = tree.DecisionTreeClassifier(random_state=42)

In [ ]:
# Fazendo o fit com os dados
clf_ac = clf_ac.fit(X_train, y_train)

In [ ]:
# Fazendo a previsão
y_pred_ac = clf_ac.predict(X_val)

- Para o **KNeighborsClassifier**

In [ ]:
# Importando
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
# Criando o classificador
clf_knn = KNeighborsClassifier(n_neighbors=3)

In [ ]:
# Fazendo o fit com os dados
clf_knn = clf_knn.fit(X_train, y_train)

In [ ]:
# Fazendo a previsão
y_pred_knn = clf_knn.predict(X_val)

- E para a **Regressão Logística**

In [ ]:
# Importando
from sklearn.linear_model import LogisticRegression

In [ ]:
# Criando o classificador
clf_rl = LogisticRegression(random_state = 42)

In [ ]:
# Fazendo o fit com os dados
clf_rl = clf_rl.fit(X_train, y_train)

In [ ]:
# Fazendo a previsão
y_pred_rl = clf_rl.predict(X_val)

- Avaliando a **acurácia**

In [ ]:
# Importando
from sklearn.metrics import accuracy_score

In [ ]:
# Para a árvore
accuracy_score(y_val, y_pred_ac)

0.6169491525423729

In [ ]:
# Para o knn
accuracy_score(y_val, y_pred_knn)

0.6610169491525424

In [ ]:
# Para a regressão logística
accuracy_score(y_val, y_pred_rl)

0.7254237288135593

- Avaliando a **matriz de confusão**

In [ ]:
# Importando
from sklearn.metrics import confusion_matrix

In [ ]:
# Para a árvore
confusion_matrix(y_val, y_pred_ac)

array([[125,  50],
       [ 63,  57]])

In [ ]:
# Para o knn
confusion_matrix(y_val, y_pred_knn)

array([[133,  42],
       [ 58,  62]])

In [ ]:
# Para a regressão logística
confusion_matrix(y_val, y_pred_rl)

array([[156,  19],
       [ 62,  58]])

### Fazendo a previsão para os dados de teste


In [ ]:
# Visualizando o X_train
X_train.head(3)

Pclass        Age  SibSp  Parch     Fare
6         1  54.000000      0      0  51.8625
718       3  29.699118      0      0  15.5000
685       2  25.000000      1      2  41.5792

In [ ]:
# Visualizando a base de teste (apenas com valores numéricos)
teste_nr.head(3)

PassengerId  Survived  Pclass   Age  SibSp  Parch    Fare
0          892         0       3  34.5      0      0  7.8292
1          893         1       3  47.0      1      0  7.0000
2          894         0       2  62.0      0      0  9.6875

In [ ]:
# Para a base de teste ser igual a base de treino, precisamos eliminar a coluna de id e a coluna Survived
X_teste = teste_nr.drop(['PassengerId', 'Survived'], axis=1)

In [ ]:
# Utilizando a regressão logística na base de teste
y_pred = clf_rl.predict(X_teste)

In [ ]:
# Utilizing the logistic regression model on the test set
y_pred = clf_rl.predict(X_teste)

In [ ]:
# Creating a new column with the prediction in the test base
teste['Survived'] = y_pred

In [ ]:
# Selecting only the Id and Survived columns for submission
submission = teste[['PassengerId', 'Survived']]

In [ ]:
# Exporting to a csv
submission.to_csv('submission.csv', index=False)