# Fazendo o deploy do nosso modelo

In [1]:
# Importando o pandas
import pandas as pd

In [ ]:
# Importando a base de treino
treino = pd.read_csv('titanic_train.csv')
treino = treino.drop('Unnamed: 0', axis=1)


In [12]:
# Visualizando as 3 primeiras linhas
treino.head(3)

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  0.9809      19.0  3.187726   1.129964       726.0  2.620939     33.98   
1  4.2232      33.0  6.189696   1.086651      1015.0  2.377049     37.46   
2  3.5488      42.0  4.821577   1.095436      1044.0  4.331950     33.79   

   Longitude  MedHouseVal  
0    -118.28        1.214  
1    -122.23        3.637  
2    -118.26        2.056

In [13]:
# Separando X e y
X_treino = treino.drop('MedHouseVal', axis=1)
y_treino = treino['MedHouseVal']

### Usando o modelo de regressão linear


In [14]:
# Importando a Regressão Linear
from sklearn.linear_model import LinearRegression

In [19]:
# Criando nosso algoritmo de regressão
reg = LinearRegression().fit(X_teste, y_teste)

In [ ]:
# Avaliando o modelo nos dados de TESTE usando apenas o score
teste = pd.read_csv('titanic_test.csv')
teste = teste.drop('Unnamed: 0', axis=1)
X_teste = teste.drop('MedHouseVal', axis=1)
y_teste = teste['MedHouseVal']

reg.score(X_teste, y_teste)

0.614382468287262

In [21]:
# Exibindo o intercept
reg.intercept_

np.float64(-36.267695160038855)

In [22]:
# Exibindo o coef
reg.coef_

array([ 4.20552266e-01,  9.51248801e-03, -8.29210167e-02,  4.45519199e-01,
        5.42879583e-06, -8.74810177e-02, -4.29583788e-01, -4.34548496e-01])

### Persistência do modelo


In [23]:
# Fazendo o dump do nosso modelo
from joblib import dump
dump(reg, 'regrassao.joblib')

['regrassao.joblib']

# **Persistencia do modelo**

In [ ]:
#importando o arquivo de teste
import pandas as pd
teste = pd.read_csv('titanic_test.csv')


In [25]:
#Fazendo load do modelo
from joblib import load
reg = load('regrassao.joblib')

In [27]:
#exibindo o intercept
reg.intercept_

np.float64(-36.267695160038855)

In [28]:
#exibindo o coef
reg.coef_

array([ 4.20552266e-01,  9.51248801e-03, -8.29210167e-02,  4.45519199e-01,
        5.42879583e-06, -8.74810177e-02, -4.29583788e-01, -4.34548496e-01])

In [29]:
#fazendo a previsão
teste = teste.drop('Unnamed: 0', axis=1)
X_teste = teste.drop('MedHouseVal', axis=1)

reg.predict(X_teste)

array([0.67815494, 1.7857306 , 2.74501868, ..., 1.24306137, 1.67262698,
       2.29219628])

In [30]:
#exportando esse arquivo
previsão = reg.predict(X_teste)

X_teste['previsão'] = previsão

X_teste.to_excel('previsão.xlsx')